//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoach
    {
        public string MaPhim { get; set; }
        public string MaCum { get; set; }
        public System.DateTime NgayKhoiChieu { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CumRap CumRap { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
