//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        public string MaPhim { get; set; }
        public string MaRap { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public string ChuoiMaSuat { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual Rap Rap { get; set; }
    }
}
