//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.Model
{
    using Project_PTUD_Desktop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Phim : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.KeHoaches = new HashSet<KeHoach>();
            this.LichChieux = new HashSet<LichChieu>();
            this.TheLoais = new HashSet<TheLoai>();
        }

        private string maPhim;
        private string tenPhim;
        private string maTheLoaiChinh;
        private Nullable<int> thoiLuong;

        public string MaPhim { get => maPhim; set { maPhim = value; OnPropertyChanged(); } }
        public string TenPhim { get => tenPhim; set { tenPhim = value; OnPropertyChanged(); } }
        public string MaTheLoaiChinh { get => maTheLoaiChinh; set { maTheLoaiChinh = value; OnPropertyChanged(); } }
        public Nullable<int> ThoiLuong { get => thoiLuong; set { thoiLuong = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoach> KeHoaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChieu> LichChieux { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheLoai> TheLoais { get; set; }
    }
}
