//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuatChieu
    {
        public string MaSuat { get; set; }
        public Nullable<int> GioBatDau { get; set; }
        public Nullable<int> PhutBatDau { get; set; }
    }
}
