//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.ModelEntity
{
    using Project_PTUD_Desktop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CumRap : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CumRap()
        {
            this.KeHoaches = new HashSet<KeHoach>();
            this.Raps = new HashSet<Rap>();
        }

        private string _maCum;
        private string _tenCum;
        private string _diaChi;
        private ICollection<KeHoach> _keHoaches;
        private ICollection<Rap> _raps;

        public string MaCum { get => _maCum; set { _maCum = value; OnPropertyChanged(); } }
        public string TenCum { get => _tenCum; set { _tenCum = value; OnPropertyChanged(); } }
        public string DiaChi { get => _diaChi; set { _diaChi = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoach> KeHoaches { get => _keHoaches; set { _keHoaches = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rap> Raps { get => _raps; set { _raps = value; OnPropertyChanged(); } }
    }
}
