//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.ModelEntity
{
    using Project_PTUD_Desktop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu : BaseViewModel
    {
        private string _maPhim;
        private string _maRap;
        private System.DateTime _ngayChieu;
        private string _chuoiMaSuat;

        public string MaPhim { get => _maPhim; set { _maPhim = value; OnPropertyChanged(); } }
        public string MaRap { get => _maRap; set { _maRap = value; OnPropertyChanged(); } }
        public System.DateTime NgayChieu { get => _ngayChieu; set { _ngayChieu = value; OnPropertyChanged(); } }
        public string ChuoiMaSuat { get => _chuoiMaSuat; set { _chuoiMaSuat = value; OnPropertyChanged(); } }
    
        public virtual Phim Phim { get; set; }
        public virtual Rap Rap { get; set; }
    }
}
