//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.ModelEntity
{
    using Project_PTUD_Desktop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Rap : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rap()
        {
            this.LichChieux = new HashSet<LichChieu>();
        }

        private string _maRap;
        private int _tongGhe;
        private string _maCum;

        public string MaRap { get => _maRap; set { _maRap = value; OnPropertyChanged(); } }
        public int TongGhe { get => _tongGhe; set { _tongGhe = value; OnPropertyChanged(); } }
        public string MaCum { get => _maCum; set { _maCum = value; OnPropertyChanged(); } }

        public virtual CumRap CumRap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChieu> LichChieux { get; set; }
    }
}
