//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PTUD_Desktop.ModelEntity
{
    using Project_PTUD_Desktop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SuatChieu : BaseViewModel
    {
        private string _maSuat;
        private Nullable<int> _gioBatDau;
        private Nullable<int> _phutBatDau;

        public string MaSuat { get => _maSuat; set { _maSuat = value; OnPropertyChanged(); } }
        public Nullable<int> GioBatDau { get => _gioBatDau; set { _gioBatDau = value; OnPropertyChanged(); } }
        public Nullable<int> PhutBatDau { get => _phutBatDau; set { _phutBatDau = value; OnPropertyChanged(); } }
    }
}
